### PR TITLE
fix: Ratelimit headers empty while running on Bun v1.0.x #418

### PR DESCRIPTION
**Pull request by MikkelSVDK**
Related to #418

### CODE REVIEW

**Review by nfriedly — APPROVED** [review]
This looks good, I think we can merge it in as-is.

However, to ensure it doesn't regress, do you think you can add automated tests in bun? Ideally run the full suite of unit tests in bun, but if that turns out to be unfeasible then perhaps just a few bun-speciffic ones, at least something that would catch this specific issue. Could be part of this PR or in a separate one.

**Comment by nfriedly** [comment]
Oh, and then `npm run format` will fix most lint issues automatically.

**Comment by MikkelSVDK** [comment]
Yes, i'll make a new PR with some tests. However im not quite sure what scheme i should follow for the tests. Should I create a folder test/bun/*.test.ts or just put them with the others, since jests only looks for *-test.?

Bun only has one requirement `Tests need ".test", "_test_", ".spec" or "_spec_" in the filename`

**Comment by nfriedly** [comment]
I think it's possible to tweak the jest config to use whatever format we want. If we renamed the existing test, would they work in bun?

**Comment by nfriedly** [comment]
OK, this will get published in v7.1.4 shortly. You might also want to file a bug on bun, since they [claim full compatibility with the `node:http` module](https://bun.sh/docs/runtime/nodejs-apis#node-http), and it defines [`setHeader` as accepting any value](https://nodejs.org/api/http.html#requestsetheadername-value).

**Pull request merged**
