### PR TITLE
Check for instance creation while handling a request

### PR DESCRIPTION
**Pull request by nfriedly**
This is one of the ideas I wrote down on https://github.com/express-rate-limit/express-rate-limit/discussions/436 - it seems to work but I'm not yet certain I want to go with it. Also, I think it needs a better name than 'middleware'.

### CODE REVIEW

**Comment by gamemaker1** [comment]
Maybe we could call it `improperCreation`?

**Comment by nfriedly** [comment]
> Maybe we could call it improperCreation?

I don't know.. the other validations are named after either the thing we're checking (e.g. `ip`), or the result we're expecting (`positiveHits`), so I don't think I want to name this one after the thing we don't want.

I have a local change where I renamed it to `creationStack`, which I like a little better. `creationCallSite` might also work. Still not 100% though.

**Comment by gamemaker1** [comment]
`callPoint`? `callStack`? otherwise `creationStack` sounds good.

**Comment by nfriedly** [comment]
Ok, I pushed the `creationStack` rename, and some tests. 

I think the help docs for this one is going to need to be a bit move detailed.

**Comment by nfriedly** [comment]
Ok, I still need to set up a redirect for the error code, but otherwise I think this is ready to go.

I might want to make a few readme tweaks before we ship it, but they're unrelated to this PR.

**Review by gamemaker1 — APPROVED** [review]
LGTM! Great work :D

**Pull request merged**
