### PR TITLE
feat: validate `totalHits` value returned from store

### PR DESCRIPTION
**Pull request by nfriedly**
Checks that the value is a positive integer. Would have helped with https://github.com/express-rate-limit/express-rate-limit/issues/353

todo:
* [x] write wiki entry
* [x] create redirect
* [x] test manually

### CODE REVIEW

**Comment by gamemaker1** [comment]
I'll finish this up and merge it rn.

Sorry I haven't been so active over the past week, I was preparing for an exam that I appeared for today.

**Comment by nfriedly** [comment]
> Sorry I haven't been so active over the past week, I was preparing for an exam that I appeared for today.

No worries, I hope your did well at the exam!

I've had a lot of ideas, and a bit of time, so it's been a good week.

**Comment by gamemaker1** [comment]
It went well, thank you!

**Comment by gamemaker1** [comment]
Tested the PR by modifying an external test (`named-imports/ts-esm`)'s `TestStore` class to return `true` from the `increment` function everytime. The validator logged an error, it worked perfectly!

**Pull request merged**
