### PR TITLE
chore: add npm run docs command, remove docs/ prefix from urls

### PR DESCRIPTION
**Pull request by nfriedly**
I added this, but it doesn't seem to actually work. The server starts, but then it just hangs. I left it running overnight last night, and there was an error, I think it was something about a recursive symlink with express-rate-limit trying to load itself from the node_modules folder, but I accidentally lost the the full error message. I have the command running again, hoping to get it to print the error message.

### CODE REVIEW

**Comment by nfriedly** [comment]
Once we get this working reliably, we should probably add a test to ensure that docs changes don't break generation of the docs site.

**Comment by nfriedly** [comment]
Ok, it finally gave up, here's the full output:

```
$ npm run docs

> express-rate-limit@7.1.1 docs
> mintlify dev

✔ Local Mintlify instance is ready. Launching your site...
node:internal/fs/utils:347
    throw err;
    ^

Error: ELOOP: too many symbolic links encountered, stat '/config/.mintlify/mint/client/public/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/node_modules/.bin/acorn'
    at Object.statSync (node:fs:1615:3)
    at /config/.mintlify/mint/node_modules/next/dist/server/lib/recursive-readdir-sync.js:17:38
    at Array.forEach (<anonymous>)
    at recursiveReadDirSync (/config/.mintlify/mint/node_modules/next/dist/server/lib/recursive-readdir-sync.js:15:12)
    at /config/.mintlify/mint/node_modules/next/dist/server/lib/recursive-readdir-sync.js:19:13
    at Array.forEach (<anonymous>)
    at recursiveReadDirSync (/config/.mintlify/mint/node_modules/next/dist/server/lib/recursive-readdir-sync.js:15:12)
    at /config/.mintlify/mint/node_modules/next/dist/server/lib/recursive-readdir-sync.js:19:13
    at Array.forEach (<anonymous>)
    at recursiveReadDirSync (/config/.mintlify/mint/node_modules/next/dist/server/lib/recursive-readdir-sync.js:15:12) {
  errno: -40,
  syscall: 'stat',
  code: 'ELOOP',
  path: '/config/.mintlify/mint/client/public/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/test/external/imports/default-import/js-cjs/node_modules/express-rate-limit/node_modules/.bin/acorn'
}

Node.js v18.16.1
```

I did an `npm ci` before running that to ensure my node_modules folder was in a pristine state.

**Comment by nfriedly** [comment]
Oh, I think it's seeing a symlink from the integration tests and running into trouble there.

**Comment by nfriedly** [comment]
Figured it out! This should make it work locally, speed it up a bit for deployments, and also get rid of the `docs/` prefix from the urls.

**Comment by nfriedly** [comment]
I'm going to go ahead and merge this one in so that the docs aren't live with the wrong URLs for very long.

**Comment by gamemaker1** [comment]
Nice!

**Pull request merged**
